### ISSUE TITLE
Define Scope

### ISSUE THREAD

**Issue by scott-coates** [Scott-Coates-Org/solo-project-1342shin#1]
# Description
Define scope for version 1.0 of the project.

## Requirements
- [x] Define milestones for each sprint.
- [x] Define final deliverable for v1.
- [x] DM your advisor for approval.
- [x] [Update your solo project repository `About` in GitHub](https://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github).

**Comment by ematkinsongit** [comment]
Instead of milestones, define issues for each milestone. Make yourself a to do list to complete your app.
